### ISSUE TITLE
很好的参考，谢谢。但是有个问题

### ISSUE THREAD

**Issue by chaseSpace** [lujinda/simplebloom#1]
bitsets的unset方法是不是应该先判断一下有没有set过，如果没有set按代码逻辑就直接set了，起了反效果。

**Comment by lujinda** [comment]
> bitsets的unset方法是不是应该先判断一下有没有set过，如果没有set按代码逻辑就直接set了，起了反效果。

感谢关注。
bloom filter其实是不能做删除的，所以unset方法，我其实根本就没有调用它。

**Comment by vannnnish** [comment]
我就说，UnSet这里怎么就有点看不懂了~
